### ISSUE TITLE
Usage in nested folder

### ISSUE THREAD

**Issue by nicolas-t** [jackyef/bundlewatch-gh-action#35]
Hello,
I'm using v0.2.0

My App structure is like this : 
Locally bundlewatch works well.
```
repo-name/ 
   - package-json // unrelated package.json
   - front/ 
       - package.json // package.json containing my bundlewatch config
```

My action is like this : 

```yml
name: Node.js CI

on:
  push:
    branches: [ mainBranch ]
  pull_request:
    branches: [ mainBranch ]

defaults:
  run:
    working-directory: ./front # note the working directory here

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Yarn install
      run: yarn install # yarn install happens in the correct directory ./front
    - name: Yarn build
      run: yarn build
    - uses: jackyef/bundlewatch-gh-action@0.2.0
      with:
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
```

When running I get this and no other output :  
![image](https://user-images.githubusercontent.com/1765930/146038418-524b2a8c-b282-4013-ab36-a4cf7a55516f.png)

If I try to put a dummy config in the root package.json bundlewatch reads the config from the root package.json and it _works_ 
With a more complete output.

Your action seems to ignore the `working-directory` property, could you check ?

Best

**Comment by jackyef** [comment]
Hey @nicolas-t 👋 

Thank you for the elaborate write up!

I was wondering, would adding an explicit path to the config file you want to use work for you? Something like the following


```yml
name: "Bundlewatch GitHub Action"

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.1.0
      - run: yarn install
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: yarn build:minify
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          bundlewatch-config: ./front/bundlewatch.config.js
```

This would require you to extract the config from `front/package.json` into a separate `front/bundlewatch.config.js`. Let me know if this works for your issue 🙂

**Comment by nicolas-t** [comment]
Hello,

Yes this is what I ended up doing.
I'm using the action like this : 
```yml
    - uses: jackyef/bundlewatch-gh-action@0.2.0
      with:
        bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        bundlewatch-config: front/.bundlewatch.config.js
```

And my config looks like this : 
```js
const bundlewatchConfig = {
    files: [
        {
            // bundlewatch github action ignores ./front working_directory
            // so we use './front/dist/assets/vendor.*.js' instead of './dist/assets/vendor.*.js',
            path: './front/dist/assets/vendor.*.js',
            compression: 'none',
            maxSize: '348 kB',
        }
    ], 
        // ...
}

module.exports = bundlewatchConfig
```

It works as espected on the github CI.

The problem is I can't call `bundlewatch --config .bundlewatch.config.js` on my local machine, because bundlewatch now looks for files in the directory `./front/front/...` which doesn't exist.

Thanks
